Check that folder does not contain path separator

diff --git a/hooks/post-finish b/hooks/post-finish
--- a/hooks/post-finish
+++ b/hooks/post-finish
@@ -23,8 +23,21 @@ rename_if_exists() {
 
 eventPayload=$(cat /dev/stdin | jq .)
 folder_id=$(echo $eventPayload | jq -r .Event.Upload.MetaData.folderId)
+
+if [[ "${folder_id}" == *\/* ]]; then
+    echo "Invalid folder ${folder_id}" >&2
+    echo "{\"detail\": \"Invalid folder ${folder_id}\"}"
+    exit 1
+fi
+
 source=$(echo $eventPayload | jq -r .Event.Upload.Storage.Path)
 filename=$(echo $eventPayload | jq -r  .Event.Upload.MetaData.filename)
+
+if [[ "${filename}" == *\/* ]]; then
+    echo "Invalid filename ${filename}" >&2
+    echo "{\"detail\": \"Invalid filename ${filename}\"}"
+    exit 1
+fi
 
 destination="${BESACE_ROOT_FOLDER}/${folder_id}/${filename}"
 echo "source=${source}" >&2
diff --git a/hooks/pre-create b/hooks/pre-create
--- a/hooks/pre-create
+++ b/hooks/pre-create
@@ -4,7 +4,13 @@ folder_id=$(echo $eventPayload | jq -r .Event.Upload.MetaData.folderId)
 source=$(echo $eventPayload | jq -r .Event.Upload.Storage.Path)
 
 echo "Receiving ${source}" >&2
-# TODO: check that folder_id does not have '/' or '.'
+
+if [[ "${folder_id}" == *\/* ]]; then
+    echo "Invalid folder ${folder_id}" >&2
+    echo "{\"detail\": \"Invalid folder ${folder_id}\"}"
+    exit 1
+fi
+
 echo "Checking folder ${BESACE_ROOT_FOLDER}/${folder_id}/" >&2
 if [ ! -d "${BESACE_ROOT_FOLDER}/${folder_id}" ]; then
     echo "Unknown folder ${folder_id}" >&2
